[project]
name = "unflattening"
version = "0.1.0"
description = "Numerical experiments for the `Unflattening by flattening` paper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.0",
    "numpy",
    "jax",
    "optax",
    "scipy",
    "qml-essentials",
    "fluksio>=0.1.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
qml-essentials = { git = "https://github.com/cirKITers/qml-essentials", rev = "b20f109a5cd19e55c9ed60f9cc672424bfe00140" }

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["F"]
